# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'Dicee App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dicee App
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

end
